version: '3.8'

services:
  db:
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/library/mysql:8.0
    container_name: mock_db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test_platform
      MYSQL_ROOT_HOST: '%'
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/docker/db-init/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p123456"]
      interval: 10s
      timeout: 20s
      retries: 15
    networks:
      - app_network

  backend:
    build: ./backend
    container_name: mock_backend
    ports:
      - "5001:5001"
    environment:
      DATABASE_URL: "mysql+mysqlconnector://root:123456@db:3306/test_platform?charset=utf8mb4"
      FLASK_DEBUG: "0"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - app_network

  frontend:
    build: ./frontend
    container_name: mock_frontend
    ports:
      - "8899:80"
    depends_on:
      - backend
    networks:
      - app_network

volumes:
  mysql_data:
  backend_data:

networks:
  app_network:

# 测试查询
# docker exec -it mock_db mysql -uroot -p123456 -e "SELECT host, user FROM mysql.user;"
# docker exec -it mock_db mysql -uroot -p123456 -e "SELECT * FROM test_platform.mocks;"
